spring:
  profiles:    active:    - local
---    
spring:
  profiles:
  - local
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource: 
    data:    - classpath:data-h2.sql 
    driverClassName: org.h2.Driver 
    url: jdbc:h2:mem:h2database
    username: sa
    password:
      jpa:    show-sql: true
    hibernate:      ddl-auto: create-drop  

